FROM python:3.6

# Install mongo - NB: This is a temporary step until we implement integration tests properly in CI
RUN apt-get update && apt-get install -y mongodb

# Start mongo
RUN mkdir -p /data/db
RUN chown -R mongodb:mongodb /data/db