from config.config import *
from dp.config.section import Section

CONFIG = Section("Global App Config")
CONFIG.APP = APP_CONFIG
CONFIG.API = API_CONFIG
CONFIG.ML = ML_CONFIG
CONFIG.ELASTIC_SEARCH = ELASTIC_SEARCH_CONFIG
CONFIG.SEARCH = SEARCH_CONFIG
CONFIG.LOGGING = LOGGING_CONFIG
