from config.config import *
from config.section import Section

CONFIG = Section("APP Config")
CONFIG.API = API_CONFIG
CONFIG.ML = ML_CONFIG
CONFIG.ELASTIC_SEARCH = ELASTIC_SEARCH_CONFIG
CONFIG.SEARCH = SEARCH_CONFIG
CONFIG.LOGGING = LOGGING_CONFIG
